#!/usr/bin/env bash

# This file is used to run "tmux-test-docker" framework tests.

# "setup" script is needed to run the tests, but it overrides some working dir
# files. To address that, "setup" is run before the tests and its actions are
# undone after.

main() {
	git clone https://github.com/slange-dev/tmux-test-docker lib/tmux-test-docker
	lib/tmux-test-docker/setup
	./run_tests
	local exit_value=$?
	lib/tmux-test-docker/setup "undo"
	exit "$exit_value"
}
main
