#!/usr/bin/env bash

# This file is a symlink from 'tmux-test-docker' plugin.
# You probably don't want to edit it.

# Run this script when running a test suite.

# global variable for script exit value
export EXIT_VALUE=0

register_failing_tests() {
	EXIT_VALUE=1
}

run_test() {
	local test_file="tests/run_tests_in_isolation"
	echo "Running test suite from: $test_file"

    # shellcheck source=/dev/null
	. "$test_file"
}

exit_message() {
	local exit_val="$1"
	echo
	if [ "$exit_val" == 0 ]; then
		echo "Success, tests pass!"
	else
		echo "Tests failed!" 1>&2
	fi
}

run_tests() {
	run_test
	local tests_exit_value="$?"
	if [ "$tests_exit_value" -gt 0 ]; then
		register_failing_tests
	fi
}

main() {
	run_tests
	exit_message "$EXIT_VALUE"
	exit "$EXIT_VALUE"
}
main
